#!/bin/sh
#
# g15daemon:   Logitech G15 Display Device Daemon.
# description: Logitech G15 Displaytreiber Daemon
#originally from http://www.g15-applets.de/g15daemon-im-systemstart-einbinden-unter-fc7-t3549.html
#I modified it to fit into debian init script conventions
PIDFILE="/var/run/g15daemon.pid"
RETVAL=3

start()
{
	echo -n "Starting g15daemon: "
  /usr/sbin/g15daemon -s
	PID=`pidof -o %PPID -x g15daemon` > ${PIDFILE} || failure
	RETVAL=$?
  echo
}

stop()
{
	echo -n "Shutting down g15daemon: "
	#if[!/usr/sbin/g15daemon -K] #maybe use it when daemon wont quit on first attempt
  #then 
  #	kill -9 $(<"$PIDFILE")
  #fi
  rm -f $PIDFILE || failure
  RETVAL=$?
  echo
}

[ -f /usr/sbin/g15daemon ] || exit 0

# See how we were called.
case "$1" in
  start)
   start
        ;;
  stop)
   stop
        ;;
  restart|reload)
   stop
   start
   ;;
  status)
     status g15daemon
     echo
     /usr/sbin/g15daemon --version
   ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|}"
        exit 1
esac

exit $RETVAL 
