#!/bin/sh
#
# g15daemon:   Logitech G15 Display Device Daemon.
#
# chkconfig:   2345 82 82
# description: Logitech G15 Displaytreiber Daemon
# processname: g15deamon
PIDFILE="/var/run/g15daemon.pid"
#

# Source function library.
#. /etc/init.d/functions


RETVAL=3

start()
{
        echo -n "Starting g15daemon: "
        /usr/sbin/g15daemon -s
	PID=`pidof -o %PPID -x g15daemon` > ${PIDFILE} || failure

   RETVAL=$?
   echo
}

stop()
{
   echo -n "Shutting down g15daemon: "
   #if[!/usr/sbin/g15daemon -K]
   #then #maybe i will use it when daemon wont quit on first attempt
   #	kill -9 $(<"$PIDFILE")
   #fi
   rm -f $PIDFILE || failure
   RETVAL=$?
   echo
}

[ -f /usr/sbin/g15daemon ] || exit 0

# See how we were called.
case "$1" in
  start)
   start
        ;;
  stop)
   stop
        ;;
  restart|reload)
   stop
   start
   ;;
  condrestart)
   [ -e "$lockfile" ] && (stop; start)
   ;;
  status)
     status g15daemon
     echo
     /usr/sbin/g15daemon --version
   ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|condrestart}"
        exit 1
esac

exit $RETVAL 
